version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mini
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mini-x
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  